// Mithril-Wrapper GL entry points -- stub table.
// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.
#include <GL/glcorearb.h>

namespace mithril {
void GlStubCalled(const char* name);
} // namespace mithril

extern "C" {

} // extern "C"
